Setup Lock Screen
level12/keg-login pull request #13
Opened 2017-04-21 00:39 UTC by nZac

2017-04-25 20:02 UTC, bladams requested changes
Looks good to me. Just a couple minor nitpicks

2017-04-25 20:02 UTC, bladams commented on keg_login/middleware.py
> +        self.exclude_routes = exclude + self.default_excluded_routes
NIT: the exclude routes could be sets/frozensets and even though it doesn't matter here, I think it's best to not use mutable default args

2017-04-25 20:08 UTC, rsyring commented on keg_login/middleware.py
> +        self.exclude_routes = exclude + self.default_excluded_routes
It's more than a NIT IMO.  You should never have a mutable default argument like this.  In this case, the way it's used doesn't matter.  But I don't even want the possibility of that coming back to bite us later.

2017-04-25 20:09 UTC, nZac commented on keg_login/middleware.py
> +        self.exclude_routes = exclude + self.default_excluded_routes
Yea, that wasn't intentional. I just missed it while I was coding. Thanks @bladams.

2017-04-25 20:10 UTC, nZac commented on keg_login/middleware.py
> +        self.exclude_routes = exclude + self.default_excluded_routes
and @rsyring :)

2017-04-27 19:54 UTC, rsyring approved these changes
There are some things I'd do differently but I'm not opposed to shipping this.  Please answer the comments if you can.

2017-04-27 19:54 UTC, rsyring commented on keg_login/forms.py
> +def make_lock_form():
Why do we return the form from a function?

2017-04-27 19:54 UTC, rsyring commented on keg_login/middleware.py
> +        return (flask.redirect(flask.url_for(self.lock_endpoint))
I don't understand why this was written this way.  The straight forward form is easier to read and shorter:

```python
if self.should_lock_out(flask.request.endpoint, flask.session):
    return flask.redirect(flask.url_for(self.lock_endpoint))
```

2017-04-27 19:54 UTC, rsyring commented on keg_login/tests/test_middleware.py
> +        cls = middleware.LockedOutMiddleware
NIT: I'd avoid using `cls` as an assigned variable name in the same way I'd avoid using `self`.

2017-05-02 15:36 UTC, bladams commented on keg_login/forms.py
> +def make_lock_form():
That seems to be the pattern for the rest of the forms in keg-login. I think this was just done for consistency.

2017-05-02 15:45 UTC, bladams approved these changes

2017-05-02 15:46 UTC, merged